### ISSUE TITLE
IndexError: Layer [Riot] not found

### ISSUE THREAD

**Issue by OlegHahm** [sgso/marz#4]
If I follow the example in the README, everything seems fine when I use the `default` example. The output looks like
```
> Got radio packet:
	Length:	63
	Src:	256
	Dst:	0
	LQI:	0
	RSSI:	0
41 88 EF CD AB FF FF 00 01 60 00 00 00 00 0C 11 40 FF 02 00 00 00 00 00 00 00 01 00 00 FF 00 01 00 FE 80 00 00 00 00 00 00 00 00 00 FF FE 00 00 01 A7 6B 16 33 00 0C 70 37 66 6F 6F 0A 1B 85 
```
which looks like a regular UDP packet with payload `foo`.

If I do the same but using the sixlowapp application (https://github.com/RIOT-OS/applications/tree/master/sixlowapp), marz will always crash and stuck in the following loop:
```
Unhandled exception from __main__.RiotProtocol.datagramReceived
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/pair/tuntap.py", line 338, in doRead
    self.protocol.datagramReceived(data, partial=0)
  File "./marz.py", line 113, in datagramReceived
    riot = Ether(frame)[Riot]
  File "/home/oleg/git/marz/scapy/packet.py", line 783, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
exceptions.IndexError: Layer [Riot] not found
```

**Comment by sgso** [comment]
It does the same for me (with all applications) and I have no idea what's going wrong. I won't fix it (but tried) because I already had some success with ng_tapdev and want to concentrate on that.
